# Generated by Django 4.0.2 on 2022-04-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrepresentative',
            name='password',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clubrepresentative',
            name='userid',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'account-manager'), (2, 'cinema-manager'), (3, 'admin')], default=3),
        ),
    ]
