# Generated by Django 4.0.2 on 2022-04-26 11:21

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='expiry_date',
            field=creditcards.models.CardExpiryField(),
        ),
    ]
