# Generated by Django 4.0.2 on 2022-05-03 18:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_alter_account_card_number_alter_account_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentQty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message=None)], verbose_name='Student Quantity')),
                ('childQty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message=None)], verbose_name='Child Quantity')),
                ('adultQty', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message=None)], verbose_name='Adult Quantity')),
                ('cancelRqst', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projectApp_booking',
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialDist', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projectApp_cinema',
            },
        ),
        migrations.RenameField(
            model_name='studentclub',
            old_name='zip_code',
            new_name='post_code',
        ),
        migrations.AddField(
            model_name='show',
            name='adultPrice',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message=None)], verbose_name='Adult Price'),
        ),
        migrations.AddField(
            model_name='show',
            name='childPrice',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message=None)], verbose_name='Child Price'),
        ),
        migrations.AddField(
            model_name='show',
            name='studentPrice',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message=None)], verbose_name='Student Price'),
        ),
        migrations.AddField(
            model_name='show',
            name='ticketsSold',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message=None)], verbose_name='Tickets Sold'),
        ),
        migrations.AlterField(
            model_name='film',
            name='age_ratting',
            field=models.CharField(choices=[('U', 'U'), ('PG', 'PG'), ('12A', '12A'), ('15+', '15+'), ('18+', '18+')], default='string', max_length=7),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('date', models.DateField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectApp.account')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectApp.booking')),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectApp.clubrepresentative')),
            ],
            options={
                'db_table': 'projectApp_transaction',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, null=True, unique=True, verbose_name='Username')),
                ('balance', models.FloatField(default=0)),
                ('validated', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectApp.account')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4, message=None), django.core.validators.MaxLengthValidator(30, message=None)], verbose_name='Cardholder Name')),
                ('cardNumber', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16, message=None), django.core.validators.MaxLengthValidator(16, message=None)], verbose_name='Card Number')),
                ('expiryDate', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5, message=None), django.core.validators.MaxLengthValidator(5, message=None)], verbose_name='Card Expiry Date')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectApp.booking')),
            ],
            options={
                'db_table': 'projectApp_card',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectApp.show'),
        ),
    ]
